### ISSUE TITLE
爬蟲資料與LineBot, 兩邊repo版本

### ISSUE THREAD

**Issue by u8989332** [Fionn88/Subsidy-Crawl#1]
Hi
      有讀過兩邊repo最新的code, 如果各執行最新的Code, 爬蟲是寫進Google Sheet, 而LineBot仍是讀MySQL.
      
 是否考慮做版號對應呢? 兩邊的一致性管理使專案好維護.  
 
 另外有個old_version建議可以刪除, 畢竟都用git, 還存在legacy code是多餘的.

      突然看到這津貼查詢專案, 覺得助人很棒, 所以提些建議, 希望專案可以更好.

**Comment by Fionn88** [comment]
您好，非常感謝您的建議

> 是否考慮做版號對應呢? 兩邊的一致性管理使專案好維護

因為目前爬蟲程式碼還在開發當中，所以才沒有很嚴謹的方式去管理。寫進 Google Sheet 這段還算是在半成品（目前在第一段而已），爬蟲主要有三段，就如 old_version 資料夾裡有三個 py 檔一樣。所以嚴格來講 old_version 在 LineBot 對應的版號是 v1.0.2，之後就沒有再更新後台的資料。而新版本的部分就如我前面所說的還在開發。

> 另外有個old_version建議可以刪除, 畢竟都用git, 還存在legacy code是多餘的.

old_version 因為是想要做為備份，還在想說怎麼樣保存在這個 repo 比較恰當，我也是覺得刪掉比較好。不知道說您這邊有什麼樣的想法呢？我目前的想法是感覺可以把 old_version 放進 release 再把 old_version 刪除，才可以做到所謂的對應版號。

**Comment by u8989332** [comment]
Git的管理方式很多種, 如果要穩定、簡易, Github flow會比較適合.
而當前old_version這個問題, 最直接是多幾個commit, 
只留舊code後並commit, 設tag v1,
刪掉舊code再換新code並commit, 設tag v2.

如果想讓整個commit歷史都變更簡潔, 可以考慮rebase, 但前提是得用push force, 且歷史資訊就亂了.

可以再多想想.

**Comment by Fionn88** [comment]
再次感謝您的回覆，我大概知道怎麼做了～

**Comment by Fionn88** [comment]
[New Tag ](https://github.com/Fionn88/Subsidy-Crawl/releases/tag/v1.0.2)
